#!/usr/bin/python3

#generate a random number with python
#user will input a guess of the number
#program will verify if number is >, < or = to random generated number
#tell how many attempts it took when number is found

import random

def guess(x):
  random_number = random.randint(1, x) #generate a random number between 1 and x
  guess = 0
  count = 0 #number of guess attempts
  while guess != random_number: #continuous loop while guess is false
    count += 1 #increment per attempt
    guess = int(input(f"Guess a number between 1 and {x} ")) #convert user input to integer
    if guess > random_number:
      print("Guess again. Your guess is too HIGH")
    elif guess < random_number:
      print("Guess again. Your guess is too LOW")
      
  #loop will break and print this if user guess is correct
  print(f"You got it! The correct number was {random_number} and you guessed {count} times.") 

##Test
#guess(10)
  
